### ISSUE TITLE
Support PHP 5.3

### ISSUE THREAD

**Issue by Mondane** [wienkit/beslist-shopitem-api-php-client#1]
I have a question, would it be much work to make this library compatible with PHP 5.3 ?

**Comment by mwienk** [comment]
Hello @Mondane, as you can see at http://php.net/eol.php the 5.3 version of PHP has been end of life for over 4 years. I will not add support for 5.3, nor do I know what impact it would have. I also strongly advise you to update your systems to a supported PHP version.
